// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqs0zbho59ZnmGxUlfVAA-FPSCAS3eSq0',
    appId: '1:691524081150:android:42bd4290e35c76a68a5caf',
    messagingSenderId: '691524081150',
    projectId: 'gaude-expenses',
    storageBucket: 'gaude-expenses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIP9tYOdFh4ix-GccqhrtZm4iHJ_HVNY8',
    appId: '1:691524081150:ios:8fdec88a163165e18a5caf',
    messagingSenderId: '691524081150',
    projectId: 'gaude-expenses',
    storageBucket: 'gaude-expenses.appspot.com',
    androidClientId:
        '691524081150-haaggn0a7si71ut98licjqdgt206uv6f.apps.googleusercontent.com',
    iosClientId:
        '691524081150-hoah8h3dia2cmoemkaad8gf5rgum13v0.apps.googleusercontent.com',
    iosBundleId: 'dev.silverhairs.gaude',
  );
}
